version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: b4you-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: b4you
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: b4you-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - '3001:3001'
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    command: npm run dev 