[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
buildCmd = "cd backend && npm install"
startCmd = "cd backend && npm start"

[deploy]
startCommand = "cd backend && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
